# Keystore Identity Credentials for MapAi APK Signing
# Registered Developer: FEVIAN ANAK DONALD

KEYSTORE_NAME_CN=FEVIAN ANAK DONALD
KEYSTORE_ORG=KAMPUNG MANTUNG MARA-U
KEYSTORE_CITY=SERIAN
KEYSTORE_POSTAL=94700
KEYSTORE_STATE=SARAWAK
KEYSTORE_COUNTRY=MY

# Distinguished Name (DNAME) string for keytool
KEYSTORE_DNAME="CN=FEVIAN ANAK DONALD, O=KAMPUNG MANTUNG MARA-U, L=SERIAN, ST=SARAWAK, C=MY"
